; VIVI Music DE — Windows installer (Inno Setup).
;
; The self-contained app image is produced by jpackage (Gradle
; `createDistributable`) and passed in through /DSourceDir. Version and icon
; paths are also supplied from the CI workflow so this file stays the single
; source of the installer layout.
;
; ---------------------------------------------------------------------------
; Branding: why the wizard used to show the Inno Setup logo
; ---------------------------------------------------------------------------
; Inno Setup has its OWN wizard artwork built in — a large image on the left of
; the Welcome and Finished pages and a small one in the header of every other
; page. When `WizardImageFile` / `WizardSmallImageFile` are not declared, that
; artwork is what the user sees, so the setup advertised Inno Setup instead of
; VIVI Music DE. Both are declared below and point at the brand bitmaps kept in
; `desktop/icons` (the same mark as the app icon): the images already existed,
; nothing referenced them.
;
; ---------------------------------------------------------------------------
; Appearance: light, dark and the VIVI Music brand
; ---------------------------------------------------------------------------
; `WizardStyle=modern dynamic` makes the setup follow Windows' own light/dark
; setting, so the appearance is never a question the user has to answer. There
; is deliberately no skin picker: `WizardStyle` is a compile-time directive and
; the run-time side is read-only (`IsDarkInstallMode` reports, it does not set),
; so a "pick a skin" list could only ever lie about a running wizard.
;
; The brand bitmaps are opaque, so dark mode gets its own pair on the deep VIVI
; violet panel (`WizardImageFileDynamicDark` / `WizardSmallImageFileDynamicDark`,
; both generated by scripts/generate_desktop_icons.py) — the white square behind
; the mark would otherwise sit on a dark wizard as a bright box.
;
; ---------------------------------------------------------------------------
; Languages
; ---------------------------------------------------------------------------
; Every language the program itself supports is selectable, over 51 entries.
; English is first and English is the default (`LanguageDetectionMethod=none`
; ignores the Windows UI language). The choice is asked for on the first screen,
; not in Inno's separate Select Language dialog, and it is asked in all 51 of
; them even though Inno translates its own wizard in only 29: [Code] builds the
; picker on the welcome page and re-runs Setup with /LANG= the moment the choice
; changes, because Inno loads its messages at startup and exposes no way to
; change them afterwards (`ActiveLanguage` and `GetUILanguage` are getters).
;
; Where Inno Setup ships a translation of its own wizard, that file is loaded
; and the whole wizard follows the choice. For the other languages the wizard
; chrome stays English — there is no translation to load — while everything THIS
; installer authors does follow the selection: the task and Run descriptions are
; `{cm:...}` lookups into Inno's own (already translated) tables, plus the
; [CustomMessages] entries below. Inno's *standard* messages are reached through
; SetupMessage(msg…): `{cm:…}` only knows [CustomMessages] and fails at run time
; on anything else (that is what broke the uninstaller; see RemovedAllText).
;
; Which translations exist depends on the compiler: Inno Setup 6 has 27 of
; them, 7 added four more. Both CI and the machine this is developed on compile
; with Inno Setup 7.1.0, so all four are there — they are still emitted behind a
; `FileExists` check, because naming a file the compiler does not have stops the
; build, and a local Inno Setup 6 install has to keep compiling too — see the
; [Languages] section.

#ifndef AppVersion
#define AppVersion "0.0.0-dev"
#endif
#ifndef InstallerVersion
#define InstallerVersion "0.0.0"
#endif
#ifndef SourceDir
#define SourceDir "."
#endif
#ifndef OutputDir
#define OutputDir "dist"
#endif
; Defaults resolve against the script's own location, so the installer can be
; compiled straight from the repo without a single /D. CI passes them as
; absolute paths anyway.
#define RepoRoot AddBackslash(SourcePath) + "..\.."
#ifndef IconFile
#define IconFile RepoRoot + "\desktop\icons\logo_vmde.ico"
#endif
#ifndef WizardImageFile
#define WizardImageFile RepoRoot + "\desktop\icons\logo_vmde_wizard.bmp"
#endif
#ifndef WizardImageFileDark
#define WizardImageFileDark RepoRoot + "\desktop\icons\logo_vmde_wizard_dark.bmp"
#endif
#ifndef WizardSmallImageFileDark
#define WizardSmallImageFileDark RepoRoot + "\desktop\icons\logo_vmde_small_dark.bmp"
#endif
#ifndef WizardSmallImageFile
#define WizardSmallImageFile RepoRoot + "\desktop\icons\logo_vmde_small.bmp"
#endif

#define AppName "VIVI Music DE"
#define AppExe "VIVIMusic.exe"
#define AppPublisher "PiBOH"
#define AppId "com.vivi.vivimusic.desktop"
#define AppURL "https://github.com/PiBOH/vivi-music-de"

[Setup]
AppId={#AppId}
AppName={#AppName}
; Inno Setup requires a numeric application version for AppVersion; the full
; `-DE` SemVer stays visible in AppVerName, in the Programs & Features entry and
; in the output filename.
AppVersion={#InstallerVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}/releases
AppComments={#AppName} — the desktop edition of VIVI Music.
DefaultDirName={autopf}\VIVIMusic
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
; Always show the "Select Destination Location" page so the user can see (and
; change) the folder the app will install into — matching the MSI installer,
; which shows the destination path.
DisableDirPage=no
; Keep an existing install's folder, shortcuts and language when the setup is
; run again (the usual upgrade in place) instead of re-asking every time.
UsePreviousAppDir=yes
UsePreviousTasks=yes
UsePreviousLanguage=yes
; NOT the Start Menu folder. Inno reuses the group name recorded by the
; previous install of the same AppId, and the earlier installers of this app
; (and the jpackage MSI) used "VIVI Music": an upgrade therefore kept the OLD
; name, which is why the same app appeared under "VIVI Music" on one machine
; and "VIVI Music DE" on another. With the group page disabled, saying no here
; is what keeps the name at DefaultGroupName on every install and upgrade.
UsePreviousGroup=no
AllowNoIcons=yes
; The installer's own log in %TEMP%: the app ships a log exporter, so a failed
; install should be diagnosable the same way.
SetupLogging=yes
AllowUNCPath=no
OutputDir={#OutputDir}
OutputBaseFilename=VIVIMusic-{#AppVersion}-setup
SetupIconFile={#IconFile}
; --- Branding: the wizard's own artwork (see the file header) ---------------
; `dynamic` follows Windows' light/dark setting (needs Inno Setup 6.6+; CI has
; 7.1.0), so `WizardImageFileDynamicDark` below is what the wizard shows when
; the user's Windows is in dark mode.
WizardStyle=modern dynamic
WizardImageFile={#WizardImageFile}
WizardSmallImageFile={#WizardSmallImageFile}
; The dark-mode counterparts, used the instant `dynamic` switches to dark.
WizardImageFileDynamicDark={#WizardImageFileDark}
WizardSmallImageFileDynamicDark={#WizardSmallImageFileDark}
; --- Language selection -----------------------------------------------------
; `none` = never guess from the Windows UI language, so the first [Languages]
; entry (English) is the default. The dialog is always shown, so the choice is
; the user's either way.
LanguageDetectionMethod=none
; No Select Language dialog: the picker is on the welcome page (see [Code]),
; and Inno's dialog would be the same question asked twice.
ShowLanguageDialog=no
; Maximize compression: the shipped image is trimmed (see MinimizeIconsJarTask in
; desktop/build.gradle.kts), so the lzma2/max + solid pass is affordable and the
; setup stays as small as possible. There are no optional [Components], so solid
; compression does not make a partial install decompress the whole block.
Compression=lzma2/max
SolidCompression=yes
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
CloseApplications=yes
RestartApplications=no
Uninstallable=yes
UninstallDisplayName={#AppName} {#AppVersion}
UninstallDisplayIcon={app}\{#AppExe}
VersionInfoCompany={#AppPublisher}
VersionInfoDescription={#AppName} desktop client
VersionInfoProductName={#AppName}
VersionInfoVersion={#InstallerVersion}
VersionInfoProductVersion={#InstallerVersion}
VersionInfoProductTextVersion={#AppVersion}
VersionInfoTextVersion={#AppVersion}
VersionInfoCopyright=Copyright (c) 2026 PiBOH

[Languages]
; --- English, always the default (first entry) ------------------------------
Name: "english"; MessagesFile: "compiler:Default.isl"

; --- Full wizard translations shipped with Inno Setup -----------------------
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "bulgarian"; MessagesFile: "compiler:Languages\Bulgarian.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
; --------- Translations only Inno Setup 7 has --------------------------------
; Chinese (both scripts), Lithuanian and Thai are not in Inno Setup 6's
; `Languages` folder — they were added in 7 — and naming a messages file the
; installed compiler does not have is a hard error ("Couldn't open include
; file"), which is how the first build of this list failed on a runner whose
; Chocolatey had installed 6.x. That runner is handed Inno Setup 7.1.0 now (see
; `.github/workflows/build-desktop-windows.yml`), so all four load there, but
; each one is still emitted only when the compiler in use really ships it: a
; local Inno Setup 6 install keeps compiling, and what it gets is the English
; messages it would have had anyway, with the small overlay in `languages\`
; supplying its name for the Select Language page.
#if FileExists(AddBackslash(CompilerPath) + "Languages\ChineseSimplified.isl")
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
#else
Name: "chinesesimplified"; MessagesFile: "compiler:Default.isl,languages\chinesesimplified.isl"
#endif
#if FileExists(AddBackslash(CompilerPath) + "Languages\ChineseTraditional.isl")
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"
#else
Name: "chinesetraditional"; MessagesFile: "compiler:Default.isl,languages\chinesetraditional.isl"
#endif
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
#if FileExists(AddBackslash(CompilerPath) + "Languages\Lithuanian.isl")
Name: "lithuanian"; MessagesFile: "compiler:Languages\Lithuanian.isl"
#else
Name: "lithuanian"; MessagesFile: "compiler:Default.isl,languages\lithuanian.isl"
#endif
Name: "norwegian"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "slovak"; MessagesFile: "compiler:Languages\Slovak.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "swedish"; MessagesFile: "compiler:Languages\Swedish.isl"
Name: "tamil"; MessagesFile: "compiler:Languages\Tamil.isl"
#if FileExists(AddBackslash(CompilerPath) + "Languages\Thai.isl")
Name: "thai"; MessagesFile: "compiler:Languages\Thai.isl"
#else
Name: "thai"; MessagesFile: "compiler:Default.isl,languages\thai.isl"
#endif
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

; --- Supported by the program, no wizard translation in Inno Setup ----------
; `LanguageName` is what the Select Language page shows, so each of these is
; still listed under its own name even though the wizard chrome falls back to
; English (Default.isl).
Name: "assamese"; MessagesFile: "compiler:Default.isl,languages\assamese.isl"
Name: "azerbaijani"; MessagesFile: "compiler:Default.isl,languages\azerbaijani.isl"
Name: "basque"; MessagesFile: "compiler:Default.isl,languages\basque.isl"
Name: "belarusian"; MessagesFile: "compiler:Default.isl,languages\belarusian.isl"
Name: "bengali"; MessagesFile: "compiler:Default.isl,languages\bengali.isl"
Name: "bosnian"; MessagesFile: "compiler:Default.isl,languages\bosnian.isl"
Name: "croatian"; MessagesFile: "compiler:Default.isl,languages\croatian.isl"
Name: "estonian"; MessagesFile: "compiler:Default.isl,languages\estonian.isl"
Name: "filipino"; MessagesFile: "compiler:Default.isl,languages\filipino.isl"
Name: "greek"; MessagesFile: "compiler:Default.isl,languages\greek.isl"
Name: "hindi"; MessagesFile: "compiler:Default.isl,languages\hindi.isl"
Name: "indonesian"; MessagesFile: "compiler:Default.isl,languages\indonesian.isl"
Name: "khmer"; MessagesFile: "compiler:Default.isl,languages\khmer.isl"
Name: "malay"; MessagesFile: "compiler:Default.isl,languages\malay.isl"
Name: "malayalam"; MessagesFile: "compiler:Default.isl,languages\malayalam.isl"
Name: "persian"; MessagesFile: "compiler:Default.isl,languages\persian.isl"
Name: "punjabi"; MessagesFile: "compiler:Default.isl,languages\punjabi.isl"
Name: "romanian"; MessagesFile: "compiler:Default.isl,languages\romanian.isl"
Name: "serbian"; MessagesFile: "compiler:Default.isl,languages\serbian.isl"
Name: "telugu"; MessagesFile: "compiler:Default.isl,languages\telugu.isl"
Name: "vietnamese"; MessagesFile: "compiler:Default.isl,languages\vietnamese.isl"

[Tasks]
; Descriptions come from Inno's own message tables — already translated in every
; language that has a wizard translation.
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; The Start Menu shortcut is unconditional: it is the normal way in, and the task
; that used to gate it could only be described with a literal English string
; (Inno ships no message for it) in all 51 languages.
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExe}"; Tasks: desktopicon

[Registry]
; Makes the app launchable by name from the Run dialog / the Explorer address
; bar (`VIVIMusic`), the way most Windows apps register themselves.
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\{#AppExe}"; ValueType: string; ValueName: ""; ValueData: "{app}\{#AppExe}"; Flags: uninsdeletekey

[Run]
Filename: "{app}\{#AppExe}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent

; ---------------------------------------------------------------------------
; Installer's own strings
; ---------------------------------------------------------------------------
; Everything else the user reads is a standard Inno Setup message and follows
; the selected language on its own. What is left is the one sentence this
; installer invented — the note above the two paths the uninstaller keeps.
[CustomMessages]
english.UninstallKept=Only your newest backup and your settings were kept:
italian.UninstallKept=Sono stati conservati solo il backup più recente e le tue impostazioni:
arabic.UninstallKept=تم الاحتفاظ فقط بأحدث نسخة احتياطية وإعداداتك:
assamese.UninstallKept=কেৱল আপোনাৰ শেহতীয়া বেকআপ আৰু আপোনাৰ ছেটিংছহে ৰখা হৈছে:
azerbaijani.UninstallKept=Yalnız ən yeni ehtiyat nüsxəniz və parametrləriniz saxlanıldı:
basque.UninstallKept=Zure azken babeskopia eta zure ezarpenak bakarrik gorde dira:
belarusian.UninstallKept=Захаваныя толькі апошняя рэзервовая копія і вашы налады:
bengali.UninstallKept=শুধু আপনার সর্বশেষ ব্যাকআপ আর আপনার সেটিংস রাখা হয়েছে:
bosnian.UninstallKept=Sačuvani su samo najnovija sigurnosna kopija i vaše postavke:
brazilianportuguese.UninstallKept=Só o seu backup mais recente e as suas configurações foram mantidos:
bulgarian.UninstallKept=Запазени са само най-новият архив и вашите настройки:
catalan.UninstallKept=Només s'han conservat la còpia de seguretat més recent i la configuració:
chinesesimplified.UninstallKept=仅保留了最新的备份和您的设置：
chinesetraditional.UninstallKept=僅保留了最新的備份與您的設定：
croatian.UninstallKept=Sačuvane su samo najnovija sigurnosna kopija i vaše postavke:
czech.UninstallKept=Zachována byla pouze nejnovější záloha a vaše nastavení:
dutch.UninstallKept=Alleen je nieuwste back-up en je instellingen zijn bewaard:
estonian.UninstallKept=Alles jäid vaid uusim varukoopia ja sinu seaded:
filipino.UninstallKept=Ang pinakabagong backup at ang iyong mga setting lang ang itinira:
finnish.UninstallKept=Vain uusin varmuuskopio ja asetuksesi säilytettiin:
french.UninstallKept=Seules votre sauvegarde la plus récente et vos réglages ont été conservés :
german.UninstallKept=Behalten wurden nur deine neueste Sicherung und deine Einstellungen:
greek.UninstallKept=Διατηρήθηκαν μόνο το πιο πρόσφατο αντίγραφο ασφαλείας και οι ρυθμίσεις σας:
hebrew.UninstallKept=נשמרו רק הגיבוי האחרון וההגדרות שלך:
hindi.UninstallKept=केवल आपका नवीनतम बैकअप और आपकी सेटिंग्स रखी गई हैं:
hungarian.UninstallKept=Csak a legfrissebb biztonsági mentés és a beállításaid maradtak meg:
indonesian.UninstallKept=Hanya cadangan terbaru dan pengaturan Anda yang disimpan:
japanese.UninstallKept=最新のバックアップと設定のみを残しました:
khmer.UninstallKept=មានតែការបម្រុងទុកចុងក្រោយបំផុត និងការកំណត់របស់អ្នកប៉ុណ្ណោះដែលត្រូវបានរក្សាទុក៖
korean.UninstallKept=최신 백업과 설정만 남겼습니다:
lithuanian.UninstallKept=Išsaugota tik naujausia atsarginė kopija ir jūsų nustatymai:
malay.UninstallKept=Hanya sandaran terbaharu dan tetapan anda disimpan:
malayalam.UninstallKept=ഏറ്റവും പുതിയ ബാക്കപ്പും നിങ്ങളുടെ ക്രമീകരണങ്ങളും മാത്രം സൂക്ഷിച്ചിരിക്കുന്നു:
norwegian.UninstallKept=Bare den nyeste sikkerhetskopien og innstillingene dine ble beholdt:
persian.UninstallKept=فقط جدیدترین پشتیبان و تنظیمات شما نگه داشته شد:
polish.UninstallKept=Zachowano tylko najnowszą kopię zapasową i Twoje ustawienia:
portuguese.UninstallKept=Apenas a cópia de segurança mais recente e as suas definições foram mantidas:
punjabi.UninstallKept=ਸਿਰਫ਼ ਤੁਹਾਡਾ ਸਭ ਤੋਂ ਨਵਾਂ ਬੈਕਅੱਪ ਅਤੇ ਤੁਹਾਡੀਆਂ ਸੈਟਿੰਗਾਂ ਰੱਖੀਆਂ ਗਈਆਂ ਹਨ:
romanian.UninstallKept=Au fost păstrate doar cea mai recentă copie de siguranță și setările tale:
russian.UninstallKept=Сохранены только последняя резервная копия и ваши настройки:
serbian.UninstallKept=Сачувани су само најновија резервна копија и ваша подешавања:
slovak.UninstallKept=Zachovaná bola iba najnovšia záloha a vaše nastavenia:
slovenian.UninstallKept=Ohranjena sta bila samo najnovejša varnostna kopija in vaše nastavitve:
spanish.UninstallKept=Solo se han conservado tu copia de seguridad más reciente y tus ajustes:
swedish.UninstallKept=Endast din senaste säkerhetskopia och dina inställningar behölls:
tamil.UninstallKept=உங்கள் சமீபத்திய காப்புப்பிரதியும் உங்கள் அமைப்புகளும் மட்டுமே வைக்கப்பட்டன:
telugu.UninstallKept=మీ తాజా బ్యాకప్ మరియు మీ సెట్టింగ్‌లు మాత్రమే ఉంచబడ్డాయి:
thai.UninstallKept=เก็บไว้เฉพาะข้อมูลสำรองล่าสุดและการตั้งค่าของคุณเท่านั้น:
turkish.UninstallKept=Yalnızca en yeni yedeğiniz ve ayarlarınız saklandı:
ukrainian.UninstallKept=Збережено лише найновішу резервну копію та ваші налаштування:
vietnamese.UninstallKept=Chỉ giữ lại bản sao lưu mới nhất và cài đặt của bạn:

; ---------------------------------------------------------------------------
; Welcome-screen strings, in the app's own words
; ---------------------------------------------------------------------------
; The welcome page is rebuilt by [Code] from these two lines, because 22 of the
; 51 languages have no Inno wizard translation and the screen that ASKS for a
; language must not be the one that stays English for them. The wording is the
; desktop app's own `welcome_title` / `welcome_desc`, so the first screen the
; setup shows and the first screen the app shows say the same thing.
;
; Generated — run `python3 scripts/generate_installer_welcome.py` instead of
; editing the block, so a change to the app's tables reaches the installer.
; --- BEGIN GENERATED: welcome strings ---
english.WelcomeTitle=Welcome to VIVI Music DE
english.WelcomeDesc=Choose your language to get started. You can change it later from Settings → Language.
azerbaijani.WelcomeTitle=VIVI Music DE-yə xoş gəlmisiniz
azerbaijani.WelcomeDesc=Başlamaq üçün dilinizi seçin. Daha sonra Ayarlar → Dil bölməsindən dəyişə bilərsiniz.
indonesian.WelcomeTitle=Selamat datang di VIVI Music DE
indonesian.WelcomeDesc=Pilih bahasa Anda untuk memulai. Anda dapat mengubahnya nanti dari Pengaturan → Bahasa.
malay.WelcomeTitle=Selamat datang ke VIVI Music DE
malay.WelcomeDesc=Pilih bahasa anda untuk bermula. Anda boleh menukarnya kemudian daripada Tetapan → Bahasa.
bosnian.WelcomeTitle=Dobrodošli u VIVI Music DE
bosnian.WelcomeDesc=Odaberite jezik za početak. Kasnije ga možete promijeniti u Postavke → Jezik.
catalan.WelcomeTitle=Benvingut a VIVI Music DE
catalan.WelcomeDesc=Trieu el vostre idioma per començar. Podeu canviar-lo més tard des de Configuració → Idioma.
german.WelcomeTitle=Willkommen bei VIVI Music DE
german.WelcomeDesc=Wählen Sie Ihre Sprache. Sie können sie später unter Einstellungen → Sprache ändern.
estonian.WelcomeTitle=Tere tulemast VIVI Music DE-sse
estonian.WelcomeDesc=Alustamiseks valige oma keel. Saate seda hiljem muuta jaotises Seaded → Keel.
spanish.WelcomeTitle=Bienvenido a VIVI Music DE
spanish.WelcomeDesc=Elige tu idioma para empezar. Puedes cambiarlo más tarde desde Ajustes → Idioma.
basque.WelcomeTitle=Ongi etorri VIVI Music DE-ra
basque.WelcomeDesc=Hasi zure hizkuntza aukeratuz. Geroago Aldatzeko ezarpenak → Hizkuntza atalean alda dezakezu.
filipino.WelcomeTitle=Maligayang pagdating sa VIVI Music DE
filipino.WelcomeDesc=Piliin ang iyong wika upang magsimula. Maaari mo itong baguhin sa ibang pagkakataon mula sa Mga Setting → Wika.
french.WelcomeTitle=Bienvenue dans VIVI Music DE
french.WelcomeDesc=Choisissez votre langue pour commencer. Vous pourrez la modifier plus tard depuis Paramètres → Langue.
croatian.WelcomeTitle=Dobrodošli u VIVI Music DE
croatian.WelcomeDesc=Odaberite jezik za početak. Kasnije ga možete promijeniti u Postavke → Jezik.
italian.WelcomeTitle=Benvenuto in VIVI Music DE
italian.WelcomeDesc=Scegli la tua lingua per iniziare. Potrai cambiarla in seguito dalle Impostazioni → Lingua.
lithuanian.WelcomeTitle=Sveiki atvykę į VIVI Music DE
lithuanian.WelcomeDesc=Pasirinkite kalbą, kad pradėtumėte. Vėliau galėsite ją pakeisti Nustatymai → Kalba.
hungarian.WelcomeTitle=Üdvözöljük a VIVI Music DE-ben
hungarian.WelcomeDesc=Kezdéshez válassza ki a nyelvét. Később a Beállítások → Nyelv menüben módosíthatja.
dutch.WelcomeTitle=Welkom bij VIVI Music DE
dutch.WelcomeDesc=Kies uw taal om te beginnen. U kunt deze later wijzigen via Instellingen → Taal.
norwegian.WelcomeTitle=Velkommen til VIVI Music DE
norwegian.WelcomeDesc=Velg språket ditt for å komme i gang. Du kan endre det senere fra Innstillinger → Språk.
polish.WelcomeTitle=Witamy w VIVI Music DE
polish.WelcomeDesc=Wybierz język, aby rozpocząć. Możesz go później zmienić w Ustawienia → Język.
portuguese.WelcomeTitle=Bem-vindo ao VIVI Music DE
portuguese.WelcomeDesc=Escolha o seu idioma para começar. Pode alterá-lo mais tarde em Definições → Idioma.
brazilianportuguese.WelcomeTitle=Bem-vindo ao VIVI Music DE
brazilianportuguese.WelcomeDesc=Escolha o seu idioma para começar. Pode alterá-lo mais tarde em Definições → Idioma.
romanian.WelcomeTitle=Bine ați venit la VIVI Music DE
romanian.WelcomeDesc=Alegeți limba pentru a începe. O puteți schimba mai târziu din Setări → Limbă.
slovak.WelcomeTitle=Vitajte vo VIVI Music DE
slovak.WelcomeDesc=Vyberte si jazyk na začiatok. Neskôr ho môžete zmeniť v Nastavenia → Jazyk.
slovenian.WelcomeTitle=Dobrodošli v VIVI Music DE
slovenian.WelcomeDesc=Izberite svoj jezik za začetek. Pozneje ga lahko spremenite v Nastavitve → Jezik.
finnish.WelcomeTitle=Tervetuloa VIVI Music DE:hen
finnish.WelcomeDesc=Valitse kieli aloittaaksesi. Voit vaihtaa sitä myöhemmin kohdassa Asetukset → Kieli.
swedish.WelcomeTitle=Välkommen till VIVI Music DE
swedish.WelcomeDesc=Välj ditt språk för att komma igång. Du kan ändra det senare från Inställningar → Språk.
vietnamese.WelcomeTitle=Chào mừng đến với VIVI Music DE
vietnamese.WelcomeDesc=Chọn ngôn ngữ của bạn để bắt đầu. Bạn có thể thay đổi sau đó từ Cài đặt → Ngôn ngữ.
turkish.WelcomeTitle=VIVI Music DE'ye hoş geldiniz
turkish.WelcomeDesc=Başlamak için dilinizi seçin. Daha sonra Ayarlar → Dil bölümünden değiştirebilirsiniz.
czech.WelcomeTitle=Vítejte ve VIVI Music DE
czech.WelcomeDesc=Vyberte jazyk pro začátek. Později jej můžete změnit v Nastavení → Jazyk.
greek.WelcomeTitle=Καλώς ήρθατε στο VIVI Music DE
greek.WelcomeDesc=Επιλέξτε τη γλώσσα σας για να ξεκινήσετε. Μπορείτε να την αλλάξετε αργότερα από Ρυθμίσεις → Γλώσσα.
belarusian.WelcomeTitle=Сардэчна запрашаем у VIVI Music DE
belarusian.WelcomeDesc=Выберыце мову, каб пачаць. Пазней яе можна змяніць у Налады → Мова.
bulgarian.WelcomeTitle=Добре дошли в VIVI Music DE
bulgarian.WelcomeDesc=Изберете език, за да започнете. Можете да го промените по-късно от Настройки → Език.
russian.WelcomeTitle=Добро пожаловать в VIVI Music DE
russian.WelcomeDesc=Выберите язык, чтобы начать. Позже его можно изменить в Настройки → Язык.
serbian.WelcomeTitle=Добродошли у VIVI Music DE
serbian.WelcomeDesc=Изаберите језик да бисте почели. Касније га можете променити у Подешавања → Језик.
ukrainian.WelcomeTitle=Ласкаво просимо до VIVI Music DE
ukrainian.WelcomeDesc=Виберіть мову, щоб почати. Пізніше її можна змінити в Налаштування → Мова.
hebrew.WelcomeTitle=ברוך הבא ל-VIVI Music DE
hebrew.WelcomeDesc=בחר את השפה שלך כדי להתחיל. תוכל לשנות אותה מאוחר יותר מהגדרות ← שפה.
arabic.WelcomeTitle=مرحبًا بك في VIVI Music DE
arabic.WelcomeDesc=اختر لغتك للبدء. يمكنك تغييرها لاحقًا من الإعدادات ← اللغة.
persian.WelcomeTitle=به VIVI Music DE خوش آمدید
persian.WelcomeDesc=برای شروع زبان خود را انتخاب کنید. می‌توانید بعداً از تنظیمات ← زبان تغییرش دهید.
hindi.WelcomeTitle=VIVI Music DE में आपका स्वागत है
hindi.WelcomeDesc=शुरू करने के लिए अपनी भाषा चुनें। आप इसे बाद में सेटिंग्स → भाषा से बदल सकते हैं।
assamese.WelcomeTitle=VIVI Music DE লৈ আদৰণি
assamese.WelcomeDesc=আৰম্ভ কৰিবলৈ আপোনাৰ ভাষা বাছনি কৰক। পিছত ছেটিংছ → ভাষা মেনুৰ পৰা সলনি কৰিব পাৰে।
bengali.WelcomeTitle=VIVI Music DE-তে স্বাগতম
bengali.WelcomeDesc=শুরু করতে আপনার ভাষা চয়ন করুন। পরে সেটিংস → ভাষা থেকে পরিবর্তন করতে পারেন।
punjabi.WelcomeTitle=VIVI Music DE ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ
punjabi.WelcomeDesc=ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ। ਤੁਸੀਂ ਇਸਨੂੰ ਬਾਅਦ ਵਿੱਚ ਸੈਟਿੰਗਾਂ → ਭਾਸ਼ਾ ਤੋਂ ਬਦਲ ਸਕਦੇ ਹੋ।
tamil.WelcomeTitle=VIVI Music DE க்கு வரவேற்கிறோம்
tamil.WelcomeDesc=தொடங்க உங்கள் மொழியைத் தேர்ந்தெடுக்கவும். பின்னர் அமைப்புகள் → மொழி என்பதிலிருந்து மாற்றலாம்.
telugu.WelcomeTitle=VIVI Music DE కి స్వాగతం
telugu.WelcomeDesc=ప్రారంభించడానికి మీ భాషను ఎంచుకోండి. తరువాత సెట్టింగ్‌లు → భాష నుండి మార్చవచ్చు.
malayalam.WelcomeTitle=VIVI Music DE ലേക്ക് സ്വാഗതം
malayalam.WelcomeDesc=ആരംഭിക്കാൻ നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക. പിന്നീട് ക്രമീകരണങ്ങൾ → ഭാഷയിൽ നിന്ന് മാറ്റാം.
thai.WelcomeTitle=ยินดีต้อนรับสู่ VIVI Music DE
thai.WelcomeDesc=เลือกภาษาของคุณเพื่อเริ่มต้น คุณสามารถเปลี่ยนได้ในภายหลังจาก การตั้งค่า → ภาษา
khmer.WelcomeTitle=ស្វាគមន៍មកកាន់ VIVI Music DE
khmer.WelcomeDesc=ជ្រើសរើសភាសារបស់អ្នកដើម្បីចាប់ផ្តើម។ អ្នកអាចផ្លាស់ប្តូរវានៅពេលក្រោយពីការកំណត់ → ភាសា។
japanese.WelcomeTitle=VIVI Music DE へようこそ
japanese.WelcomeDesc=開始するには言語を選択してください。後で設定 → 言語から変更できます。
chinesesimplified.WelcomeTitle=欢迎使用 VIVI Music DE
chinesesimplified.WelcomeDesc=选择您的语言以开始使用。之后可在设置 → 语言中更改。
chinesetraditional.WelcomeTitle=歡迎使用 VIVI Music DE
chinesetraditional.WelcomeDesc=選擇您的語言以開始使用。之後可在設定 → 語言中變更。
korean.WelcomeTitle=VIVI Music DE에 오신 것을 환영합니다
korean.WelcomeDesc=시작하려면 언어를 선택하세요. 나중에 설정 → 언어에서 변경할 수 있습니다.; --- END GENERATED: welcome strings ---

[Code]
var
  InstallDetailsMemo: TNewMemo;
  UninstallDetailsMemo: TNewMemo;
  LastInstallLine: String;
  UninstallCleanupOk: Boolean;
  LanguageLabel: TNewStaticText;
  LanguageCombo: TNewComboBox;
  LangIds: TArrayOfString;
  LangNames: TArrayOfString;
  LangWords: TArrayOfString;

// Uninstall any previously-installed jpackage MSI of this app. The MSI and this
// Inno Setup installer are two different installer technologies, so each
// registers its own entry under "Apps & features". Removing the MSI here keeps
// a single uninstall entry when the user installs the .exe after the .msi.
procedure UninstallExistingMsi();
var
  RootKeys: array of String;
  Names: TArrayOfString;
  I, J: Integer;
  DisplayName, UninstallString: String;
  ResultCode: Integer;
begin
  SetArrayLength(RootKeys, 2);
  RootKeys[0] := 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall';
  RootKeys[1] := 'SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall';
  for J := 0 to GetArrayLength(RootKeys) - 1 do
  begin
    if RegGetSubkeyNames(HKLM, RootKeys[J], Names) then
    begin
      for I := 0 to GetArrayLength(Names) - 1 do
      begin
        if RegQueryStringValue(HKLM, RootKeys[J] + '\' + Names[I], 'DisplayName', DisplayName) and
           RegQueryStringValue(HKLM, RootKeys[J] + '\' + Names[I], 'UninstallString', UninstallString) then
        begin
          if (Pos('VIVI', Uppercase(DisplayName)) > 0) and (Pos('MSIEXEC', Uppercase(UninstallString)) > 0) then
          begin
            Exec('msiexec.exe', '/x ' + Names[I] + ' /qn /norestart', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
          end;
        end;
      end;
    end;
  end;
end;

// ---------------------------------------------------------------------------
// Details/log box helpers
// ---------------------------------------------------------------------------
// Inno Setup 6 removed the built-in "Show details" memo/button that existed in
// Inno Setup 5 (there is no WizardForm.Memo / DetailsMemo / DetailsButton), so
// the log box is created at runtime below the progress gauge and filled with
// the files being extracted (install) and the cleanup steps (uninstall).

procedure AddInstallLine(const Line: String);
begin
  if InstallDetailsMemo = nil then Exit;
  if Line = '' then Exit;
  if InstallDetailsMemo.Lines.Count > 2000 then
    InstallDetailsMemo.Lines.Clear;
  InstallDetailsMemo.Lines.Add(Line);
end;

// The uninstall details box is only usable while the uninstall progress page
// exists: Inno Setup tears that page down as soon as the file-removal step is
// over, and touching the memo afterwards raises "Control 'TNewMemo' has no
// parent window". Every write is therefore guarded - a dead box must never
// abort the uninstallation - and the line falls back to the uninstall log file
// in %TEMP% so the record is never lost.
function UninstallLogPath(): String;
begin
  Result := GetEnv('TEMP') + '\VIVIMusic-uninstall.log';
end;

procedure AddUninstallLine(const Line: String);
begin
  if Line = '' then Exit;
  if UninstallDetailsMemo <> nil then begin
    try
      if UninstallDetailsMemo.Lines.Count > 2000 then
        UninstallDetailsMemo.Lines.Clear;
      UninstallDetailsMemo.Lines.Add(Line);
      Exit;
    except
      { The details box is gone: keep the record on disk instead. }
    end;
  end;
  SaveStringToFile(UninstallLogPath(), Line + #13#10, True);
end;

procedure CreateInstallDetailsMemo();
begin
  if InstallDetailsMemo <> nil then Exit;
  InstallDetailsMemo := TNewMemo.Create(WizardForm);
  InstallDetailsMemo.Parent := WizardForm.InstallingPage;
  InstallDetailsMemo.Left := 0;
  InstallDetailsMemo.Top := WizardForm.ProgressGauge.Top + WizardForm.ProgressGauge.Height + ScaleY(8);
  InstallDetailsMemo.Width := WizardForm.InstallingPage.ClientWidth;
  InstallDetailsMemo.Height := WizardForm.InstallingPage.ClientHeight - InstallDetailsMemo.Top - ScaleY(8);
  InstallDetailsMemo.ReadOnly := True;
  InstallDetailsMemo.ScrollBars := ssVertical;
  InstallDetailsMemo.WordWrap := False;
  InstallDetailsMemo.Font.Name := 'Consolas';
  InstallDetailsMemo.Font.Size := 8;
  LastInstallLine := '';
end;

// "<app> was successfully removed from your computer."
//
// UninstalledAll lives in Inno's own [Messages] table, not in [CustomMessages],
// so `{cm:UninstalledAll}` cannot find it: the uninstaller dies with
// "Internal error: Unknown custom message name "UninstalledAll" in "cm"
// constant" the moment this box is built (reported with a screenshot on
// 1.54.18). It is read the way a standard message has to be read, and %1 is
// filled in with FmtMessage, which is also what makes the sentence follow the
// language the setup was run in.
function RemovedAllText(): String;
begin
  Result := FmtMessage(SetupMessage(msgUninstalledAll), ['{#AppName}']);
end;

// Removes a Start Menu folder an older installer left under another name.
//
// The jpackage MSI, and the first versions of this installer, put the shortcuts
// in a "VIVI Music" folder; this one uses "VIVI Music DE" (DefaultGroupName) and
// keeps it on every upgrade (UsePreviousGroup=no). The leftovers of the other
// name would otherwise sit next to the new entry forever. Only a folder that
// really holds this app's shortcut is touched, and the removal is written to the
// install log, so a folder that is not ours is left alone.
procedure RemoveStaleStartMenuGroup();
var
  Roots: TArrayOfString;
  I: Integer;
  Folder: String;
begin
  SetArrayLength(Roots, 2);
  Roots[0] := ExpandConstant('{commonprograms}');
  Roots[1] := ExpandConstant('{userprograms}');
  for I := 0 to GetArrayLength(Roots) - 1 do begin
    Folder := Roots[I] + '\VIVI Music';
    if DirExists(Folder) then begin
      if FileExists(Folder + '\VIVIMusic.lnk') or FileExists(Folder + '\VIVI Music.lnk') then begin
        if DelTree(Folder, True, True, True) then
          AddInstallLine('Removed the old Start Menu folder: ' + Folder)
        else
          AddInstallLine('Could not remove the old Start Menu folder: ' + Folder);
      end;
    end;
  end;
end;

procedure CreateUninstallDetailsMemo();
begin
  if UninstallDetailsMemo <> nil then Exit;
  if UninstallProgressForm = nil then Exit;
  if UninstallProgressForm.InstallingPage = nil then Exit;
  try
    UninstallDetailsMemo := TNewMemo.Create(UninstallProgressForm);
    UninstallDetailsMemo.Parent := UninstallProgressForm.InstallingPage;
  except
    { No box on this machine: AddUninstallLine writes to the log file instead. }
    Exit;
  end;
  UninstallDetailsMemo.Left := 0;
  UninstallDetailsMemo.Top := UninstallProgressForm.ProgressBar.Top + UninstallProgressForm.ProgressBar.Height + ScaleY(8);
  UninstallDetailsMemo.Width := UninstallProgressForm.InstallingPage.ClientWidth;
  UninstallDetailsMemo.Height := UninstallProgressForm.InstallingPage.ClientHeight - UninstallDetailsMemo.Top - ScaleY(8);
  UninstallDetailsMemo.ReadOnly := True;
  UninstallDetailsMemo.ScrollBars := ssVertical;
  UninstallDetailsMemo.WordWrap := False;
  UninstallDetailsMemo.Font.Name := 'Consolas';
  UninstallDetailsMemo.Font.Size := 8;
end;

// ---------------------------------------------------------------------------
// Uninstall cleanup: keep the newest *.vivide.backup and device-sync.json,
// delete everything else
// ---------------------------------------------------------------------------
// The app keeps its user data under `%USERPROFILE%\.vivimusic`: settings
// (device-sync.json), playlists, imported fonts, the backup history
// (`backups\*.vivide.backup`) and every cache (downloaded updates, audio,
// video/canvas, lyrics, logs, extracted helper libraries and artwork). On
// uninstall exactly two things survive: the NEWEST .vivide.backup - a full
// restore point with settings and playlists - and device-sync.json. Every other
// file, older backups included, and every cache are deleted.

{ "prefix_YYYYMMDD_HHMMSS.vivide.backup" -> "YYYYMMDD_HHMMSS". The timestamp is
  always the last 15 characters before the extension, so comparing those
  strings is chronological even when the prefixes differ (auto_backup_* vs
  vivimusic-de_*). }
function BackupTimestamp(const FileName: String): String;
var
  Base: String;
begin
  Base := Copy(FileName, 1, Length(FileName) - 14);
  if Length(Base) < 15 then
    Result := ''
  else
    Result := Copy(Base, Length(Base) - 14, 15);
end;

procedure BackupAndCleanUserData();
var
  ViviDir, BackupsDir, Entry, ItemPath, KeepBackup, KeepKey, Key: String;
  FindRec: TFindRec;
begin
  ViviDir := GetEnv('USERPROFILE') + '\.vivimusic';
  if not DirExists(ViviDir) then begin
    AddUninstallLine('No user data found at ' + ViviDir + ' - nothing to clean.');
    Exit;
  end;

  BackupsDir := ViviDir + '\backups';

  { Keep the newest backup: the largest timestamp wins. }
  KeepBackup := '';
  KeepKey := '';
  if FindFirst(BackupsDir + '\*.vivide.backup', FindRec) then begin
    try
      repeat
        Key := BackupTimestamp(FindRec.Name);
        if (Key <> '') and (Key > KeepKey) then begin
          KeepKey := Key;
          KeepBackup := FindRec.Name;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
  if KeepBackup = '' then
    AddUninstallLine('No .vivide.backup found - nothing to keep.')
  else
    AddUninstallLine('Keeping the newest backup: ' + KeepBackup);

  { Delete everything under ~/.vivimusic except device-sync.json and backups. }
  if FindFirst(ViviDir + '\*', FindRec) then begin
    try
      repeat
        Entry := FindRec.Name;
        if (Entry = '.') or (Entry = '..') then Continue;
        ItemPath := ViviDir + '\' + Entry;
        if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then begin
          if CompareText(Entry, 'backups') <> 0 then begin
            DelTree(ItemPath, True, True, True);
            AddUninstallLine('Removed cache: ' + Entry);
          end;
        end else begin
          if CompareText(Entry, 'device-sync.json') <> 0 then begin
            DeleteFile(ItemPath);
            AddUninstallLine('Removed file: ' + Entry);
          end;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;

  { Inside backups/, only the newest .vivide.backup survives. }
  if FindFirst(BackupsDir + '\*', FindRec) then begin
    try
      repeat
        Entry := FindRec.Name;
        if (Entry = '.') or (Entry = '..') then Continue;
        if CompareText(Entry, KeepBackup) <> 0 then begin
          ItemPath := BackupsDir + '\' + Entry;
          if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
            DelTree(ItemPath, True, True, True)
          else
            DeleteFile(ItemPath);
          AddUninstallLine('Removed old backup: ' + Entry);
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;

  AddUninstallLine('Uninstall cleanup complete. Only the newest backup and device-sync.json remain.');
end;

// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
// The welcome screen's language picker
// ---------------------------------------------------------------------------
// Inno Setup loads its messages once, at startup — 6.7 and 7 both expose only
// `ActiveLanguage` and `GetUILanguage`, and both are read-only — so a wizard
// cannot be re-languaged while it runs. The picker therefore sits on the first
// screen and re-runs Setup with `/LANG=` as soon as the choice changes: the new
// instance opens on this same page, in the chosen language, in about a second.
// That is also why `WizardStyle` has no skin picker to keep it company (see the
// file header) — the appearance, unlike the language, has no `/DARK` switch to
// restart with.
//
// Everything the page shows at that moment comes from this installer's own
// tables — `[CustomMessages]` for the two welcome strings, `LoadLanguages` for
// the picker — and not from Inno's message table.
//
// An unattended run never restarts itself: `WizardSilent` (/SILENT and
// /VERYSILENT) skips the picker entirely.

procedure AddLanguage(const Id, Display, Word: String);
begin
  SetArrayLength(LangIds, GetArrayLength(LangIds) + 1);
  LangIds[GetArrayLength(LangIds) - 1] := Id;
  SetArrayLength(LangNames, GetArrayLength(LangNames) + 1);
  LangNames[GetArrayLength(LangNames) - 1] := Display;
  SetArrayLength(LangWords, GetArrayLength(LangWords) + 1);
  LangWords[GetArrayLength(LangWords) - 1] := Word;
end;

// Generated — run `python3 scripts/generate_installer_welcome.py` instead of
// editing the calls, so a change to the app's tables reaches the installer.
procedure LoadLanguages();
begin
  SetArrayLength(LangIds, 0);
  SetArrayLength(LangNames, 0);
  SetArrayLength(LangWords, 0);
{ --- BEGIN GENERATED: languages --- }
  AddLanguage('english', 'English', 'Language');
  AddLanguage('azerbaijani', 'Azərbaycanca', 'Dil');
  AddLanguage('indonesian', 'Bahasa Indonesia', 'Bahasa');
  AddLanguage('malay', 'Bahasa Melayu', 'Bahasa');
  AddLanguage('bosnian', 'Bosanski', 'Jezik');
  AddLanguage('catalan', 'Català', 'Idioma');
  AddLanguage('german', 'Deutsch', 'Sprache');
  AddLanguage('estonian', 'Eesti', 'Keel');
  AddLanguage('spanish', 'Español', 'Idioma');
  AddLanguage('basque', 'Euskara', 'Hizkuntza');
  AddLanguage('filipino', 'Filipino', 'Wika');
  AddLanguage('french', 'Français', 'Langue');
  AddLanguage('croatian', 'Hrvatski', 'Jezik');
  AddLanguage('italian', 'Italiano', 'Lingua');
  AddLanguage('lithuanian', 'Lietuvių', 'Kalba');
  AddLanguage('hungarian', 'Magyar', 'Nyelv');
  AddLanguage('dutch', 'Nederlands', 'Taal');
  AddLanguage('norwegian', 'Norsk', 'Språk');
  AddLanguage('polish', 'Polski', 'Język');
  AddLanguage('portuguese', 'Português (Portugal)', 'Idioma');
  AddLanguage('brazilianportuguese', 'Português Brasileiro', 'Idioma do app');
  AddLanguage('romanian', 'Română', 'Limbă');
  AddLanguage('slovak', 'Slovenčina', 'Jazyk');
  AddLanguage('slovenian', 'Slovenščina', 'Jezik');
  AddLanguage('finnish', 'Suomi', 'Kieli');
  AddLanguage('swedish', 'Svenska', 'Språk');
  AddLanguage('vietnamese', 'Tiếng Việt', 'Ngôn ngữ');
  AddLanguage('turkish', 'Türkçe', 'Uygulama dili');
  AddLanguage('czech', 'Čeština', 'Jazyk');
  AddLanguage('greek', 'Ελληνικά', 'Γλώσσα');
  AddLanguage('belarusian', 'Беларуская', 'Мова');
  AddLanguage('bulgarian', 'Български', 'Език');
  AddLanguage('russian', 'Русский', 'Язык');
  AddLanguage('serbian', 'Српски', 'Jezik');
  AddLanguage('ukrainian', 'Українська', 'Мова');
  AddLanguage('hebrew', 'עִבְרִית', 'שפה');
  AddLanguage('arabic', 'العربية', 'اللغة');
  AddLanguage('persian', 'فارسی', 'زبان برنامه');
  AddLanguage('hindi', 'हिन्दी', 'भाषा');
  AddLanguage('assamese', 'অসমীয়া', 'ভাষা');
  AddLanguage('bengali', 'বাংলা', 'ভাষা');
  AddLanguage('punjabi', 'ਪੰਜਾਬੀ', 'ਭਾਸ਼ਾ');
  AddLanguage('tamil', 'தமிழ்', 'மொழி');
  AddLanguage('telugu', 'తెలుగు', 'భాష');
  AddLanguage('malayalam', 'മലയാളം', 'ഭാഷ');
  AddLanguage('thai', 'ไทย', 'ภาษา');
  AddLanguage('khmer', 'ខ្មែរ', 'ភាសា');
  AddLanguage('japanese', '日本語', '言語');
  AddLanguage('chinesesimplified', '简体中文', '语言');
  AddLanguage('chinesetraditional', '繁體中文', '語言');
  AddLanguage('korean', '한국어', '언어');{ --- END GENERATED: languages --- }
end;

// The index of the language this process is running in.
function CurrentLanguageIndex(): Integer;
var
  I: Integer;
begin
  Result := 0;
  for I := 0 to GetArrayLength(LangIds) - 1 do
    if CompareText(LangIds[I], ActiveLanguage) = 0 then begin
      Result := I;
      Exit;
    end;
end;

// Everything on the command line except a `/LANG=`, so a run that was given one
// by hand does not restart with two of them.
function WithoutLangParam(const Params: String): String;
var
  Rest, Token: String;
  Space: Integer;
begin
  Result := '';
  Rest := Trim(Params);
  while Rest <> '' do begin
    Space := Pos(' ', Rest);
    if Space = 0 then begin
      Token := Rest;
      Rest := '';
    end else begin
      Token := Copy(Rest, 1, Space - 1);
      Rest := Trim(Copy(Rest, Space + 1, Length(Rest)));
    end;
    if (Token <> '') and (Pos('/LANG=', Uppercase(Token)) <> 1) then
      Result := Trim(Result + ' ' + Token);
  end;
end;

procedure RelaunchWithLanguage(const Id: String);
var
  Params: String;
  ResultCode: Integer;
begin
  Params := Trim(WithoutLangParam(GetCmdTail()) + ' /LANG=' + Id);
  // `{srcexe}` is the running setup, and this process is already elevated by
  // now (`PrivilegesRequired=admin`), so the second instance does not ask again.
  if not Exec(ExpandConstant('{srcexe}'), Params, '', SW_SHOWNORMAL, ewNoWait, ResultCode) then begin
    // Nothing to restart with: keep the wizard on the language it is really in,
    // so the picker never claims a language the setup is not speaking.
    Log('language picker: could not restart setup with /LANG=' + Id);
    LanguageCombo.ItemIndex := CurrentLanguageIndex();
    LanguageLabel.Caption := LangWords[CurrentLanguageIndex()];
    Exit;
  end;
  WizardForm.Close;
end;

procedure ApplyWelcomeStrings();
begin
  WizardForm.WelcomeLabel1.Caption := ExpandConstant('{cm:WelcomeTitle}');
  WizardForm.WelcomeLabel2.Caption := ExpandConstant('{cm:WelcomeDesc}');
end;

procedure LanguageComboChanged(Sender: TObject);
begin
  if LanguageCombo.ItemIndex < 0 then Exit;
  // The label follows the pick immediately, so the choice is felt even before
  // the restarted instance has loaded its own messages.
  LanguageLabel.Caption := LangWords[LanguageCombo.ItemIndex];
  if CompareText(LangIds[LanguageCombo.ItemIndex], ActiveLanguage) = 0 then Exit;
  RelaunchWithLanguage(LangIds[LanguageCombo.ItemIndex]);
end;

procedure BuildLanguagePicker();
var
  I: Integer;
begin
  LoadLanguages();
  if GetArrayLength(LangIds) = 0 then Exit;
  ApplyWelcomeStrings();

  // The picker cannot hang below Inno's own welcome labels: WelcomeLabel2 is a
  // fixed-height box whose bottom edge is pinned 4 pixels above the page's
  // bottom edge (`AutoSize` is off, and Inno only moves that box up when its
  // own heading shrinks), so a control placed "under" it - which is where the
  // first version of this picker was placed - lands outside the visible page
  // and is never seen. Both controls are anchored to the bottom edge of the
  // page instead: visible in every language, whatever the description says.
  // The combo needs 40 units of that bottom edge (a combo box picks its own
  // height from its style, so it cannot be measured from Pascal Script), and
  // the label takes the 28 units above the combo.
  LanguageLabel := TNewStaticText.Create(WizardForm);
  LanguageLabel.Parent := WizardForm.WelcomePage;
  LanguageLabel.Left := WizardForm.WelcomeLabel1.Left;
  LanguageLabel.Top := WizardForm.WelcomePage.ClientHeight - ScaleY(40) - ScaleY(28);
  LanguageLabel.AutoSize := True;
  // A custom style is active in dark mode (and in light mode whenever Windows'
  // own style is not used), and a script-set font colour is ignored while one
  // is: opting this label out of `seFont` is what keeps it readable in both
  // appearances. Same technique as Inno's own CodeClasses.iss example.
  LanguageLabel.StyleElements := LanguageLabel.StyleElements - [seFont];
  if IsDarkInstallMode then
    LanguageLabel.Font.Color := clWhite
  else
    LanguageLabel.Font.Color := clBlack;

  LanguageCombo := TNewComboBox.Create(WizardForm);
  LanguageCombo.Parent := WizardForm.WelcomePage;
  LanguageCombo.Left := LanguageLabel.Left;
  LanguageCombo.Top := WizardForm.WelcomePage.ClientHeight - ScaleY(40);
  LanguageCombo.Width := ScaleX(260);
  LanguageCombo.Style := csDropDownList;
  for I := 0 to GetArrayLength(LangNames) - 1 do
    LanguageCombo.Items.Add(LangNames[I]);
  LanguageCombo.ItemIndex := CurrentLanguageIndex();
  LanguageLabel.Caption := LangWords[LanguageCombo.ItemIndex];
  LanguageCombo.OnChange := @LanguageComboChanged;
end;

// ---------------------------------------------------------------------------
// Installer events
// ---------------------------------------------------------------------------

procedure InitializeWizard();
begin
  CreateInstallDetailsMemo();
  // The first screen is the one that asks for the language, and /SILENT runs
  // must never be handed a control that restarts the setup.
  if not WizardSilent then
    BuildLanguagePicker();
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
    UninstallExistingMsi()
  else if CurStep = ssPostInstall then
    // After the files are in place, so the new Start Menu entry exists first.
    RemoveStaleStartMenuGroup();
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = wpInstalling then
    CreateInstallDetailsMemo();
end;

// Mirror the file currently being extracted into the details box so the user
// sees a live log of what is being written (the IS5 "Show details" behavior).
procedure CurInstallProgressChanged(Current, Total: Integer);
var
  Line: String;
begin
  Line := Trim(WizardForm.FilenameLabel.Caption);
  if (Line <> '') and (Line <> LastInstallLine) then begin
    LastInstallLine := Line;
    AddInstallLine(Line);
  end;
end;

// ---------------------------------------------------------------------------
// Uninstaller events
// ---------------------------------------------------------------------------

procedure InitializeUninstallProgressForm();
begin
  { Deliberately empty: at this point the uninstall progress page exists but is
    not on screen yet, so it has no window handle and parenting a control to it
    is unreliable. The details box is created in
    CurUninstallStepChanged(usUninstall) instead, once the page is really up -
    and that is the ONLY window in which the memo can be written, so the box is
    created, filled and left alone inside that one step. }
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  KeptPaths: String;
begin
  if CurUninstallStep = usUninstall then begin
    CreateUninstallDetailsMemo();
    AddUninstallLine('Removing application files…');
    { The user-data cleanup runs here - in the same step as the details box -
      instead of in usPostUninstall. Two reasons: the progress page (and with it
      the box) is destroyed as soon as the file-removal step is over, so a later
      write would only be possible in the log file; and keeping it here means
      every cleanup line is shown in the box while the page is still up. }
    UninstallCleanupOk := True;
    try
      BackupAndCleanUserData();
    except
      UninstallCleanupOk := False;
      AddUninstallLine('Cleanup failed - user data left untouched.');
      AddUninstallLine('Details: ' + UninstallLogPath());
    end;
  end
  else if CurUninstallStep = usPostUninstall then begin
    { The first sentence below is Inno's own, so it follows the selected
      language; the two paths need no translating. }
    KeptPaths := GetEnv('USERPROFILE') + '\.vivimusic\backups' + #13#10 +
                 GetEnv('USERPROFILE') + '\.vivimusic\device-sync.json';
    if UninstallCleanupOk then
      MsgBox(
        RemovedAllText() + #13#10 + #13#10 +
        ExpandConstant('{cm:UninstallKept}') + #13#10 + KeptPaths,
        mbInformation, MB_OK)
    else
      MsgBox(
        RemovedAllText() + #13#10 + #13#10 +
        'The cache cleanup could not be completed, so your data was left untouched at:' + #13#10 +
        GetEnv('USERPROFILE') + '\.vivimusic' + #13#10 + #13#10 +
        'Log: ' + UninstallLogPath(),
        mbInformation, MB_OK);
  end;
end;