#!/usr/bin/env python3
"""
Regenerate the desktop emoji coverage list (`EmojiCoverage.kt`) from the two
emoji fonts the desktop app bundles.

Run from the repo root:

    python3 scripts/build_desktop_emoji_coverage.py
    python3 scripts/build_desktop_emoji_coverage.py --check

Why this exists. Compose Desktop does not fall back to a second font on its own:
a character the current font does not carry is laid out as its `.notdef` box, the
"question mark in a rhombus" the changelog was reported to show next to Fixed,
Changed and Commits while only Added (a codepoint the bundled font happened to
carry) came out. `MarkdownFonts` therefore hands each codepoint of a rendered
line to the emoji family that owns it, and to do that it has to know what each
bundled family actually carries. That is this file's list, read straight out of
the fonts' `cmap` tables instead of being maintained by hand.

The two bundled fonts:

  * `fonts/TwemojiColorEmoji.ttf` — the colour face. Twemoji Mozilla (COLRv0),
    built by the twemoji-colr project from the Twemoji artwork. It paints colour
    under this app's Compose/Skiko renderer; the Noto Color Emoji subset that
    used to sit here had a COLR table this renderer painted as nothing, which is
    why the changelog emoji went blank and then monochrome. See
    `desktop/src/main/resources/fonts/README.md`.
  * `fonts/NotoEmoji.ttf` — the monochrome face (SIL OFL 1.1), the fallback for
    every emoji the colour face does not have.

Both lists hold every codepoint the font's `cmap` maps above ASCII (`0x7F`).
ASCII is left out on purpose: the emoji fonts also map `#`, `*`, the digits and
the space (as keycap bases), and asking an emoji family for those drew every
changelog digit inside its wide cell, which is what made `1.54.11`, `#97` and
even the word gaps letter-spaced.

`EmojiCoverage.kt` is generated: do not edit it by hand, run this script. With
`--check` the script only verifies the committed file matches the fonts and
exits 1 when it does not, so a font swap that forgets to regenerate is caught.
"""

import argparse
import os
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

try:
    from fontTools.ttLib import TTFont
except ImportError:  # pragma: no cover - a developer machine without fonttools
    print(
        "fontTools is not installed. Install it with:\n"
        "    python3 -m pip install fonttools",
        file=sys.stderr,
    )
    raise SystemExit(2)

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESKTOP = os.path.join(
    REPO, "desktop", "src", "main", "kotlin", "com", "music", "vivi", "desktop"
)

# resource file -> Kotlin property in EmojiCoverage
FONTS = {
    "colorEmoji": os.path.join(
        REPO, "desktop", "src", "main", "resources", "fonts", "TwemojiColorEmoji.ttf"
    ),
    "monochromeEmoji": os.path.join(
        REPO, "desktop", "src", "main", "resources", "fonts", "NotoEmoji.ttf"
    ),
}

OUT = os.path.join(DESKTOP, "EmojiCoverage.kt")

HEADER = '''package com.music.vivi.desktop

/**
 * The codepoints the two bundled emoji fonts actually carry.
 *
 * [MarkdownFonts] consults these before handing a character to an emoji family:
 * a codepoint the colour font does not have goes to the monochrome one (or to a
 * symbol font) instead of being requested from a font that would draw the tofu
 * box. GENERATED by `scripts/build_desktop_emoji_coverage.py`, which reads the
 * `cmap` of both bundled fonts, so a font swap cannot leave a stale list behind.
 * Do not edit by hand: run the script.
 *
 * Only codepoints above ASCII are listed. The fonts also map `#`, `*`, the
 * digits and the space (keycap bases) and asking an emoji family for those drew
 * every digit of a version number inside its wide cell.
 */
internal object EmojiCoverage {
'''


def cmap_codepoints(path):
    """Every codepoint above ASCII the font maps, through any cmap subtable."""
    font = TTFont(path, lazy=True)
    codepoints = set()
    for table in font["cmap"].tables:
        codepoints.update(table.cmap.keys())
    font.close()
    return {cp for cp in codepoints if cp > 0x7F}


def render(sets):
    lines = [HEADER]
    for name in ("colorEmoji", "monochromeEmoji"):
        values = sorted(sets[name])
        lines.append(f"    val {name}: Set<Int> = setOf(")
        for start in range(0, len(values), 10):
            chunk = values[start : start + 10]
            lines.append("        " + ", ".join(f"0x{cp:X}" for cp in chunk) + ",")
        lines.append("    )")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="only verify the committed EmojiCoverage.kt is up to date",
    )
    args = parser.parse_args()

    for name, path in FONTS.items():
        if not os.path.isfile(path):
            raise SystemExit(f"missing bundled font for {name}: {path}")

    sets = {name: cmap_codepoints(path) for name, path in FONTS.items()}
    for name, path in FONTS.items():
        print(f"{name:18} {len(sets[name]):5} codepoints above ASCII in {os.path.basename(path)}")

    generated = render(sets)
    if args.check:
        if not os.path.isfile(OUT):
            print(f"{OUT} does not exist; run the script without --check")
            return 1
        with open(OUT, encoding="utf-8") as fh:
            current = fh.read()
        if current != generated:
            print(
                f"{OUT} is out of date: run "
                "python3 scripts/build_desktop_emoji_coverage.py"
            )
            return 1
        print(f"{OUT} is up to date")
        return 0

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(generated)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
