#!/usr/bin/env python3
"""Generate AUR packaging assets (PKGBUILD + SRCINFO) for a Vivi Music DE release.

Run by .github/workflows/auto-release.yml right before the GitHub release is
created. The generated files are attached to the release as assets, so Arch
users (or an AUR maintainer) can grab the PKGBUILD, drop it in a directory
with the matching SRCINFO, and run `makepkg -si` locally.

The source tarball is pinned to the exact commit of the release
(`https://github.com/<repo>/archive/<sha>.tar.gz`), because the release tag is
created only at publish time, after this step runs. Pinning the SHA keeps the
checksum stable and guarantees the package always matches the release content.

Usage:
    python3 scripts/generate_aur_pkgbuild.py --out DIR --sha <commit-sha> \
        [--repo PiBOH/vivi-music]
"""

import argparse
import hashlib
import os
import sys
import urllib.request

# version.txt layout (see desktop/build.gradle.kts):
#   1 mobile version, 2 mobile version code, 3 mobile channel,
#   4 DE version, 5 DE version code, 6 DE channel
def read_version_file(path="version.txt"):
    lines = []
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if line and not line.startswith("#"):
                lines.append(line)
    return {
        "mobile": lines[0] if len(lines) > 0 else "0.0.0",
        "de": lines[3] if len(lines) > 3 else "0.0.0",
        "channel": lines[5] if len(lines) > 5 else "stable",
    }


def release_tag(version):
    """Mirrors the tag logic in auto-release.yml (no 'v' prefix, channel suffix)."""
    full = "{mobile}_DE-{de}".format(**version)
    channel = version["channel"].strip().lower()
    if channel and channel != "stable":
        return "{}-{}".format(full, channel)
    return full


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="Output directory for PKGBUILD + SRCINFO")
    parser.add_argument("--sha", required=True, help="Git commit SHA the release is built from")
    parser.add_argument("--repo", default="PiBOH/vivi-music", help="GitHub repo (owner/name)")
    args = parser.parse_args()

    version = read_version_file()
    tag = release_tag(version)
    # AUR pkgver forbids '-' (channels like -nightly are turned into '.').
    pkgver = version["de"].replace("-", ".")
    tarball_url = "https://github.com/{}/archive/{}.tar.gz".format(args.repo, args.sha)

    # Download and checksum the source tarball (best-effort: a network hiccup
    # must never break the release, so fall back to SKIP with a warning).
    sha256 = "SKIP"
    try:
        with urllib.request.urlopen(tarball_url, timeout=180) as resp:
            data = resp.read()
        sha256 = hashlib.sha256(data).hexdigest()
        print("Source tarball: {} ({} bytes, sha256 {})".format(tarball_url, len(data), sha256[:16]))
    except Exception as exc:  # noqa: BLE001
        print("WARNING: could not download source tarball ({}); using SKIP checksum.".format(exc), file=sys.stderr)

    os.makedirs(args.out, exist_ok=True)

    pkgbuild = """\
# Maintainer: PiBOH <https://github.com/PiBOH>
# Generated by scripts/generate_aur_pkgbuild.py — release {tag}
pkgname=vivi-music-de
pkgver={pkgver}
pkgrel=1
pkgdesc="VIVI Music DE — native desktop edition of VIVI Music (Material 3 music player for YouTube Music)"
arch=('x86_64')
url="https://github.com/{repo}"
license=('custom')
depends=('libglvnd' 'fontconfig' 'libx11' 'libxtst')
makedepends=('jdk21-openjdk' 'unzip')
options=('!strip')
source=("vivi-music::https://github.com/{repo}/archive/{sha}.tar.gz")
sha256sums=('{sha256}')

build() {{
    cd "$srcdir/vivi-music"
    ./gradlew :desktop:createDistributable --no-daemon
}}

package() {{
    local appdir="$srcdir/vivi-music/desktop/build/compose/binaries/main/app/VIVIMusic"
    install -d "$pkgdir/opt/vivi-music-de"
    cp -a "$appdir/." "$pkgdir/opt/vivi-music-de/"
    install -Dm644 "$srcdir/vivi-music/desktop/icons/logo_vmde.png" \
        "$pkgdir/usr/share/icons/hicolor/512x512/apps/vivi-music-de.png"
    install -d "$pkgdir/usr/share/applications" "$pkgdir/usr/bin"
    cat > "$pkgdir/usr/share/applications/vivi-music-de.desktop" <<'DESKTOP'
[Desktop Entry]
Name=Vivi Music DE
Comment=Desktop music player for YouTube Music
Exec=/opt/vivi-music-de/bin/VIVIMusic %U
Icon=vivi-music-de
Terminal=false
Type=Application
Categories=AudioVideo;Audio;Player;
StartupWMClass=VIVIMusic
DESKTOP
    ln -s /opt/vivi-music-de/bin/VIVIMusic "$pkgdir/usr/bin/vivi-music-de"
}}
""".format(tag=tag, pkgver=pkgver, repo=args.repo, sha=args.sha, sha256=sha256)

    srcinfo = """\
pkgbase = vivi-music-de
\tpkgdesc = VIVI Music DE — native desktop edition of VIVI Music (Material 3 music player for YouTube Music)
\tpkgver = {pkgver}
\tpkgrel = 1
\turl = https://github.com/{repo}
\tarch = x86_64
\tlicense = custom
\tdepends = libglvnd
\tdepends = fontconfig
\tdepends = libx11
\tdepends = libxtst
\tmakedepends = jdk21-openjdk
\tmakedepends = unzip
\toptions = !strip
\tsource = vivi-music::https://github.com/{repo}/archive/{sha}.tar.gz
\tsha256sums = {sha256}
""".format(pkgver=pkgver, repo=args.repo, sha=args.sha, sha256=sha256)

    pkgbuild_path = os.path.join(args.out, "PKGBUILD")
    srcinfo_path = os.path.join(args.out, "SRCINFO")
    with open(pkgbuild_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(pkgbuild)
    with open(srcinfo_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(srcinfo)
    print("Wrote {} and {} (release tag: {}, pkgver: {})".format(pkgbuild_path, srcinfo_path, tag, pkgver))


if __name__ == "__main__":
    main()
